### PR TITLE
refactor: new documentation structure, better usage docs

### PR DESCRIPTION
**Pull request by mikapfl**
# Pull request

Please confirm that this pull request has done the following:

- [ ] Tests added
- [x] Documentation added (where applicable)
- [x] Description in a ``.rst`` file in the directory ``changelog_unreleased`` added - remember to include a ``*`` to make it a bullet point

## Description

* [x] Convert documentation to myst, uses markdown
* [x] Use layout which is better suited
* [x] Convert all notebooks to be self-contained (had to remove the FAOstat reading notebook, the file was not obtainable from FAOstat anymore)
* [x] rewrite "select and view" part of usage documentation
* [x] rewrite the rest of the usage documentation
* [x] rewrite API documentation
* [x] check rest of documentation for consistency
* [x] fix API documentation on rtd
* [x] figure out what to do about the changelog
* [ ] add the primap logo into the documentation, gotta have images

## Notes

This is unfortunately a bigger restructuring, but our current model for the usage documentation was not sustainable anymore, it was super hard to find anything.

### CODE REVIEW

**Comment by mikapfl** [comment]
API docs are a mess still. I'm pretty close to writing a small script which creates the necessary pages for a sane API documentation itself.

Things to figure out:
* autosummary
* autosummary accessors
* what did we do so far?

I hope I can figure this out tomorrow, API docs were pretty annoying so far, but our use case is also surprisingly complex (with the accessors, and normal functions, and numpy-style docstrings).

**Comment by mikapfl** [comment]
Things which *didn't* work:
* autoapi
* autodoc2

**Comment by mikapfl** [comment]
Okay, next step is to write a small script which autogenerates `docs/source/api/*.rst` and somehow make sure it is run when new functions are introduced.

**Comment by mikapfl** [comment]
The script which writes out the top-level api documentation was actually required. Everything else doesn't cleanly work with our weird setup, which has:
* numpy docstrings
* rst format in docstrings (I'd like to change this to markdown, so not a blocker to change the setup)
* most of the functionality in an xarray accessor

E.g. griffe2md essentially doesn't know what to do with the xarray accessor.

**Comment by mikapfl** [comment]
@crdanielbusch @JGuetschow Probably not useful to dive into details of the changes on a syntax level, there are **lots** of changes all over the place because I migrated the documentation into a new structure (subfolders) and a new format (MyST, based on markdown instead of reStructuredText).

Note:
* you can check out the new documentation here: https://primap2--264.org.readthedocs.build/en/264/
* docstrings still have to be written in reStructuredText. I tried hard to migrate them to markdown, but the technology is not yet here
* API docs are pretty functional now, with cross-linking and everything.
* but the class documentations are a bit redundant, with methods and attributes twice, and attributes properly visible only once. I have to stop somewhere in my quest to fix things, and since this is merely lightly annoying, I just accepted it for now.

I still have to figure out how to add the primap logo, but I hope that's not too hard.

**Comment by mikapfl** [comment]
Also important: I adopted towncrier for the changelog fragments, see `changelog/README.md` or one of the existing changelog files in `changelog/` for how it works.

**Review by crdanielbusch — APPROVED** [review]

**Comment by JGuetschow** [comment]
> Also important: I adopted towncrier for the changelog fragments, see `changelog/README.md` or one of the existing changelog files in `changelog/` for how it works.

How do I add more than one news item of the same type, e.g. fix several bugs or add several new features? Multiple paragraphs in one file?

**Comment by JGuetschow** [comment]
> @crdanielbusch @JGuetschow Probably not useful to dive into details of the changes on a syntax level, there are **lots** of changes all over the place because I migrated the documentation into a new structure (subfolders) and a new format (MyST, based on markdown instead of reStructuredText).

The new docs look good, but there is one issue: in dark mode the xarray output is very hard to read as it's all different shades of grey. As it's  easy to switch modes it's not a big issue though.

**Comment by mikapfl** [comment]
> Multiple paragraphs in one file?
Yes, that should work.

> The new docs look good, but there is one issue: in dark mode the xarray output is very hard to read as it's all different shades of grey. As it's easy to switch modes it's not a big issue though.

I'll see if I can fix that easily (maybe just disabling dark mode if xarray doesn't support it)

**Comment by mikapfl** [comment]
Re dark mode: It seems it is hard to fix or completely disable, but we now default to light mode, so users only get the dark mode if they explicitly click on the dark mode button and then they should be able to also switch back if it annoys them that things are hard to read.

**Pull request merged**
