### PR TITLE
Use pandas 2

### PR DESCRIPTION
**Pull request by mikapfl**
# Pull request

Please confirm that this pull request has done the following:

- [ ] Tests added
- [ ] Documentation added (where applicable)
- [x] Description in a ``.rst`` file in the directory ``changelog_unreleased`` added - remember to include a ``*`` to make it a bullet point

## Description

Updated our pandas dependency to version 2

closes: #256

### CODE REVIEW

**Comment by mikapfl** [comment]
Only very minimal fixes were necessary to have passing and warnings-free tests locally. Now investigating what happens on windows CI.

**Comment by mikapfl** [comment]
Yeah, we're not yet ready for numpy 2. For downscaling we need certain accelerated functions in xarray, which can be obtained from either the bottleneck package or the numbagg package. But neither bottleneck nor numba are ready for numpy 2, yet. So we will have to wait a bit more for numpy 2.

**Comment by JGuetschow** [comment]
The warning come from the `pm2io` module. But I think from the tested functions like `from_interchange_format`. I'll check again.

**Comment by JGuetschow** [comment]
```
primap2/pm2io/_GHG_inventory_reading.py:166: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_stacked = df_nir.stack([0, 1], dropna=True).to_frame()
```
So far I could always just adopt the new implementation without problems, but I've not checked yet if that works in all cases. I assume not because the warning would be useless if there's nothing to warn about

I also get warnings about setting values in chained assignments, but I don't have an example for a primap2 function throwing them. If I find one I'll add it here.

**Comment by mikapfl** [comment]
We discussed that we don't need to fix the warnings in `_GHG_inventory_reading.py` because the function is only needed for reading deprecated report formats.

**Pull request merged**
