### PR TITLE
Faster merge

### PR DESCRIPTION
**Pull request by mikapfl**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Description in a ``.rst`` file in the directory ``changelog_unreleased`` added - remember to include a ``*`` to make it a bullet point

## Description

Use xarray's `DataArray.combine_first` function to do the heavy lifting in `pr.merge` instead of our own recursive algorithm. This is at least 10x faster than the previous algorithm for our tests, and easier to understand.

### CODE REVIEW

**Comment by mikapfl** [comment]
@JGuetschow do you know if there are any issues still blocking this? It is quite a large performance enhancement, so I'd like to merge it, but also don't want to break your workflows.

**Comment by JGuetschow** [comment]
I don't know of any issues, but so far I've not looked at it, just overlooked the notification. Sorry for that. 
Your strategy is to split discrepancy detection and merging, correct. You first calculate the differences and throw an error / warning based on that and later just merge with combine_first. This should work fine.

**Comment by mikapfl** [comment]
Yeah, and I also changed the format of the warnings. I don't know if you are already using the warnings downstream and expect a specific format.

**Comment by JGuetschow** [comment]
No, I'm not expecting a specific format (an just realized that the entity was missing in my output)

**Pull request merged**
